= Helloworld in Java

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repository shows how to configure link:https://github.com/features/actions[GitHub Actions], link:https://jreleaser.org/[JReleaser], and link:https://github.com/jreleaser/jreleaser-slsa[JReleaser SLSA builder] to:

 * compile a helloworld app
 * assemble a zip distributions with JReleaser, including SBOM and SWID tag
 * create rolling early-access releases with JReleaser on every push to `main` branch
 * generate SLSA attestation upon release

IMPORTANT: JReleaser requires 2 additional inputs that may be set as environment variables, `JRELEASER_PROJECT_VERSION` and `JRELEASER_GITHUB_TOKEN`. 
More information about environment variable configuration may be found in the link:https://jreleaser.org/guide/latest/reference/environment.html[guide].

## Requirements

 - Java 11 or greater.
 - JReleaser 1.17.0 or greater.

We recommend link:https://sdkman.io/[SDKMan] to install these requirements.

## Build

Use the provided Maven wrapper script to build the project:

```sh
$ ./mvnw verify
```

Next, assemble the Zip distribution by invoking

```sh
$ jreleaser assemble
```

You may perform a release by invoking

```sh
$ jreleaser release
```

NOTE: SLSA attestation can only be generated when running on GitHub Actions.

